name: Build and deploy Node.js app to Azure Web App - app-web-frontend

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build
          ls -la build || echo "⚠️ No se generó la carpeta build"

      - name: Upload build artifact
        if: ${{ hashFiles('build/**/*') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: build

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F191198A80B9417481EB7C61D8AA97FB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_485325EB645D42B29BB38E836C254822 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3D959D0794764F778E161D35F9B7D5AF }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: app-web-frontend
          slot-name: Production
          package: build
